# Generated by Django 5.0.4 on 2024-05-01 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_id_alter_userwallet_id_paymenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
